// Auto-generated locale file for en-GB
// This file is generated by running 'npm run build:i18n'
// Do not edit this file directly - edit the JSON files in i18n/locales/ instead

export default {
  "navigation": {
    "home": "Home",
    "components": "Components",
    "layouts": "Layouts",
    "about": "About",
    "settings": "Settings",
    "account": "Account",
    "login": "Login",
    "dashboard": "Dashboard",
    "someOtherLink": "Some other link",
    "childLinksTitle": {
      "uiComponents": "UI Components",
      "uiLayouts": "UI Layouts",
      "settings": "Settings",
      "manageAccount": "Manage Your Account"
    },
    "placeholderLink": "Holding link",
    "screenReader": {
      "settings": "Settings"
    }
  },
  "global": {
    "siteName": "SRCDEV Design System"
  },
  "pages": {
    "account": {
      "login": {
        "header": "Login to Your Account",
        "description": "Access your account using your email and password."
      }
    },
    "index": {
      "header": "SRCDEV Design System",
      "description": "Visual demos of typography, layout, and components."
    },
    "settings": {
      "locale-switcher": {
        "header": "Select Language",
        "description": "Choose your preferred language from the list."
      }
    }
  }
} as const