// Auto-generated locale file for ar-YE
// This file is generated by running 'npm run build:i18n'
// Do not edit this file directly - edit the JSON files in i18n/locales/ instead

export default {
  "components": {
    "footer": {
      "home": "الرئيسية",
      "components": "المكونات",
      "layouts": "التخطيطات",
      "about": "حول",
      "settings": "الإعدادات",
      "account": "الحساب",
      "login": "تسجيل الدخول",
      "dashboard": "لوحة التحكم",
      "someOtherLink": "رابط آخر",
      "childLinksTitle": {
        "uiComponents": "مكونات واجهة المستخدم",
        "uiLayouts": "تخطيطات واجهة المستخدم",
        "settings": "الإعدادات",
        "manageAccount": "إدارة حسابك"
      },
      "placeholderLink": "رابط مؤقت",
      "screenReader": {
        "settings": "الإعدادات"
      }
    },
    "navigation": {
      "home": "الرئيسية",
      "components": "المكونات",
      "layouts": "التخطيطات",
      "about": "حول",
      "settings": "الإعدادات",
      "account": "الحساب",
      "login": "تسجيل الدخول",
      "dashboard": "لوحة التحكم",
      "someOtherLink": "رابط آخر",
      "childLinksTitle": {
        "uiComponents": "مكونات واجهة المستخدم",
        "uiLayouts": "تخطيطات واجهة المستخدم",
        "settings": "الإعدادات",
        "manageAccount": "إدارة حسابك"
      },
      "placeholderLink": "رابط مؤقت",
      "screenReader": {
        "settings": "الإعدادات"
      }
    }
  },
  "global": {
    "siteName": "SRCDEV Design System"
  },
  "pages": {
    "account": {
      "forgotten-password": {
        "header": "نسيت كلمة المرور",
        "description": "إعادة تعيين كلمة المرور الخاصة بك باستخدام بريدك الإلكتروني."
      },
      "login": {
        "header": "تسجيل الدخول إلى حسابك",
        "description": "قم بالوصول إلى حسابك باستخدام بريدك الإلكتروني وكلمة المرور."
      }
    },
    "index": {
      "header": "SRCDEV Design System",
      "description": "نماذج بصرية للخطوط والتخطيط والمكونات.",
      "exampleI18nTitle": "بيانات مثال من i18n",
      "exampleI18nArray": [
        {
          "id": "exampleValue",
          "name": "مثال على القيمة",
          "count": 3,
          "items": [
            {
              "id": "item1",
              "name": "العنصر 1"
            },
            {
              "id": "item2",
              "name": "العنصر 2"
            },
            {
              "id": "item3",
              "name": "العنصر 3"
            }
          ]
        },
        {
          "id": "exampleValue2",
          "name": "مثال على القيمة 2",
          "count": 5,
          "items": [
            {
              "id": "item4",
              "name": "العنصر 4"
            },
            {
              "id": "item5",
              "name": "العنصر 5"
            }
          ]
        },
        {
          "id": "exampleValue3",
          "name": "مثال على القيمة 3",
          "count": 2,
          "items": [
            {
              "id": "item6",
              "name": "العنصر 6"
            },
            {
              "id": "item7",
              "name": "العنصر 7"
            }
          ]
        },
        {
          "id": "exampleValue4",
          "name": "مثال على القيمة 4",
          "count": 0,
          "items": []
        }
      ]
    },
    "legal": {
      "terms": {
        "meta": {
          "title": "Terms and Conditions",
          "description": "Legal information regarding the use of the SRCDEV Design System."
        },
        "header": "Terms and Conditions",
        "subheader": "Welcome to the SRCDEV Design System",
        "sections": [
          {
            "text": "Introduction",
            "link": "#introduction",
            "section": [
              {
                "title": "What is the SRCDEV Design System?",
                "content": [
                  "The SRCDEV Design System is a comprehensive collection of design principles, components, and guidelines developed to ensure consistency and efficiency in creating user interfaces across various platforms. It serves as a single source of truth for designers and developers, promoting best practices and enhancing collaboration within the SRCDEV community.",
                  "By adhering to the SRCDEV Design System, teams can streamline their workflows, reduce redundancy, and deliver high-quality digital experiences that align with SRCDEV's brand identity and user expectations."
                ]
              }
            ]
          }
        ]
      }
    },
    "settings": {
      "colour-mode-switcher": {
        "header": "تبديل وضع الألوان",
        "description": "اختر وضع الألوان المفضل لديك، أو اضبطه على \"تلقائي\" لاتباع إعدادات النظام"
      },
      "locale-switcher": {
        "header": "اختر اللغة",
        "description": "اختر لغتك المفضلة من القائمة."
      }
    }
  }
} as const