// Auto-generated locale file for ar-YE
// This file is generated by running 'npm run build:i18n'
// Do not edit this file directly - edit the JSON files in i18n/locales/ instead

export default {
  "navigation": {
    "home": "الرئيسية",
    "components": "المكونات",
    "layouts": "التخطيطات",
    "about": "حول",
    "settings": "الإعدادات",
    "account": "الحساب",
    "login": "تسجيل الدخول",
    "dashboard": "لوحة التحكم",
    "someOtherLink": "رابط آخر",
    "childLinksTitle": {
      "uiComponents": "مكونات واجهة المستخدم",
      "uiLayouts": "تخطيطات واجهة المستخدم",
      "settings": "الإعدادات",
      "manageAccount": "إدارة حسابك"
    },
    "placeholderLink": "رابط مؤقت",
    "screenReader": {
      "settings": "الإعدادات"
    }
  },
  "global": {
    "siteName": "SRCDEV Design System"
  },
  "pages": {
    "account": {
      "login": {
        "header": "تسجيل الدخول إلى حسابك",
        "description": "قم بالوصول إلى حسابك باستخدام بريدك الإلكتروني وكلمة المرور."
      }
    },
    "index": {
      "header": "SRCDEV Design System",
      "description": "نماذج بصرية للخطوط والتخطيط والمكونات."
    },
    "settings": {
      "locale-switcher": {
        "header": "اختر اللغة",
        "description": "اختر لغتك المفضلة من القائمة."
      }
    }
  }
} as const