// Auto-generated locale file for en-GB
// This file is generated by running 'npm run build:i18n'
// Do not edit this file directly - edit the JSON files in i18n/locales/ instead

export default {
  "components": {
    "footer": {
      "home": "Home",
      "components": "Components",
      "layouts": "Layouts",
      "about": "About",
      "settings": "Settings",
      "account": "Account",
      "login": "Login",
      "dashboard": "Dashboard",
      "someOtherLink": "Some other link",
      "childLinksTitle": {
        "uiComponents": "UI Components",
        "uiLayouts": "UI Layouts",
        "settings": "Settings",
        "manageAccount": "Manage Your Account"
      },
      "placeholderLink": "Holding link",
      "screenReader": {
        "settings": "Settings"
      }
    },
    "navigation": {
      "home": "Home",
      "components": "Components",
      "layouts": "Layouts",
      "about": "About",
      "settings": "Settings",
      "account": "Account",
      "login": "Login",
      "dashboard": "Dashboard",
      "someOtherLink": "Some other link",
      "childLinksTitle": {
        "uiComponents": "UI Components",
        "uiLayouts": "UI Layouts",
        "settings": "Settings",
        "manageAccount": "Manage Your Account"
      },
      "placeholderLink": "Holding link",
      "screenReader": {
        "settings": "Settings"
      }
    }
  },
  "global": {
    "siteName": "SRCDEV Design System"
  },
  "pages": {
    "account": {
      "forgotten-password": {
        "header": "Forgotten Password",
        "description": "Reset your password using your email."
      },
      "login": {
        "header": "Login to Your Account",
        "description": "Access your account using your email and password."
      }
    },
    "index": {
      "header": "SRCDEV Design System Homepage",
      "description": "Visual demos of typography, layout, and components.",
      "exampleI18nTitle": "Example data from i18n",
      "exampleI18nArray": [
        {
          "id": "exampleValue",
          "name": "Example Value",
          "count": 3,
          "items": [
            {
              "id": "item1",
              "name": "Item 1"
            },
            {
              "id": "item2",
              "name": "Item 2"
            },
            {
              "id": "item3",
              "name": "Item 3"
            }
          ]
        },
        {
          "id": "exampleValue2",
          "name": "Example Value 2",
          "count": 5,
          "items": [
            {
              "id": "item4",
              "name": "Item 4"
            },
            {
              "id": "item5",
              "name": "Item 5"
            }
          ]
        },
        {
          "id": "exampleValue3",
          "name": "Example Value 3",
          "count": 2,
          "items": [
            {
              "id": "item6",
              "name": "Item 6"
            },
            {
              "id": "item7",
              "name": "Item 7"
            }
          ]
        },
        {
          "id": "exampleValue4",
          "name": "Example Value 4",
          "count": 0,
          "items": []
        }
      ]
    },
    "legal": {
      "terms": {
        "meta": {
          "title": "Terms and Conditions",
          "description": "Legal information regarding the use of the SRCDEV Design System."
        },
        "header": "Terms and Conditions",
        "subheader": "Welcome to the SRCDEV Design System",
        "pageContent": {
          "title": "Contents"
        },
        "sections": [
          {
            "title": "Introduction",
            "link": "introduction",
            "section": [
              {
                "title": "What is the SRCDEV Design System?",
                "content": [
                  "The SRCDEV Design System is a comprehensive collection of design principles, components, and guidelines developed to ensure consistency and efficiency in creating user interfaces across various platforms. It serves as a single source of truth for designers and developers, promoting best practices and enhancing collaboration within the SRCDEV community.",
                  "By adhering to the SRCDEV Design System, teams can streamline their workflows, reduce redundancy, and deliver high-quality digital experiences that align with SRCDEV's brand identity and user expectations."
                ]
              },
              {
                "title": "Acceptance of Terms",
                "content": [
                  "By accessing and using the SRCDEV Design System, you agree to comply with and be bound by these Terms and Conditions. If you do not agree to these terms, please do not use the SRCDEV Design System.",
                  [
                    "These Terms and Conditions may be updated from time to time. It is your responsibility to review them periodically for any changes. Your continued use of the SRCDEV Design System after any modifications constitutes your acceptance of the updated terms.",
                    "We recommend bookmarking this page to stay informed about any changes to our terms.",
                    "If you have any questions or concerns about these Terms and Conditions, please contact us at [support{'@'}srcdev.com](mailto:support{'@'}srcdev.com).",
                    "Example with markdown and a link to [Google](https://www.google.com)."
                  ]
                ]
              },
              {
                "title": "Changes to Terms",
                "content": [
                  "We reserve the right to modify or update these Terms and Conditions at any time without prior notice. It is your responsibility to review these terms periodically for any changes. Your continued use of the SRCDEV Design System after any modifications constitutes your acceptance of the updated terms."
                ]
              }
            ]
          }
        ]
      }
    },
    "settings": {
      "colour-mode-switcher": {
        "header": "Switch Colour Mode",
        "description": "Choose your preferred colour, or set 'auto' for system setting"
      },
      "locale-switcher": {
        "header": "Select Language",
        "description": "Choose your preferred language from the list."
      }
    }
  }
} as const