// Auto-generated locale file for en-GB
// This file is generated by running 'npm run build:i18n'
// Do not edit this file directly - edit the JSON files in i18n/locales/ instead

export default {
  "components": {
    "footer": {
      "home": "Home",
      "components": "Components",
      "layouts": "Layouts",
      "about": "About",
      "settings": "Settings",
      "account": "Account",
      "login": "Login",
      "dashboard": "Dashboard",
      "someOtherLink": "Some other link",
      "childLinksTitle": {
        "uiComponents": "UI Components",
        "uiLayouts": "UI Layouts",
        "settings": "Settings",
        "manageAccount": "Manage Your Account"
      },
      "placeholderLink": "Holding link",
      "screenReader": {
        "settings": "Settings"
      }
    },
    "navigation": {
      "home": "Home",
      "components": "Components",
      "layouts": "Layouts",
      "about": "About",
      "settings": "Settings",
      "account": "Account",
      "login": "Login",
      "dashboard": "Dashboard",
      "someOtherLink": "Some other link",
      "childLinksTitle": {
        "uiComponents": "UI Components",
        "uiLayouts": "UI Layouts",
        "settings": "Settings",
        "manageAccount": "Manage Your Account"
      },
      "placeholderLink": "Holding link",
      "screenReader": {
        "settings": "Settings"
      }
    }
  },
  "global": {
    "siteName": "SRCDEV Design System"
  },
  "pages": {
    "account": {
      "forgotten-password": {
        "header": "Forgotten Password",
        "description": "Reset your password using your email."
      },
      "login": {
        "header": "Login to Your Account",
        "description": "Access your account using your email and password."
      }
    },
    "index": {
      "header": "SRCDEV Design System Homepage",
      "description": "Visual demos of typography, layout, and components.",
      "exampleI18nTitle": "Example data from i18n",
      "exampleI18nArray": [
        {
          "id": "exampleValue",
          "name": "Example Value",
          "count": 3,
          "items": [
            {
              "id": "item1",
              "name": "Item 1"
            },
            {
              "id": "item2",
              "name": "Item 2"
            },
            {
              "id": "item3",
              "name": "Item 3"
            }
          ]
        },
        {
          "id": "exampleValue2",
          "name": "Example Value 2",
          "count": 5,
          "items": [
            {
              "id": "item4",
              "name": "Item 4"
            },
            {
              "id": "item5",
              "name": "Item 5"
            }
          ]
        },
        {
          "id": "exampleValue3",
          "name": "Example Value 3",
          "count": 2,
          "items": [
            {
              "id": "item6",
              "name": "Item 6"
            },
            {
              "id": "item7",
              "name": "Item 7"
            }
          ]
        },
        {
          "id": "exampleValue4",
          "name": "Example Value 4",
          "count": 0,
          "items": []
        }
      ]
    },
    "settings": {
      "colour-mode-switcher": {
        "header": "Switch Colour Mode",
        "description": "Choose your preferred colour, or set 'auto' for system setting"
      },
      "locale-switcher": {
        "header": "Select Language",
        "description": "Choose your preferred language from the list."
      }
    }
  }
} as const