// Auto-generated locale file for zh-CN
// This file is generated by running 'npm run build:i18n'
// Do not edit this file directly - edit the JSON files in i18n/locales/ instead

export default {
  "components": {
    "footer": {
      "home": "首页",
      "components": "组件",
      "layouts": "布局",
      "about": "关于",
      "settings": "设置",
      "account": "账户",
      "login": "登录",
      "dashboard": "仪表板",
      "someOtherLink": "其他链接",
      "childLinksTitle": {
        "uiComponents": "用户界面组件",
        "uiLayouts": "用户界面布局",
        "settings": "设置",
        "manageAccount": "管理您的账户"
      },
      "placeholderLink": "占位链接",
      "screenReader": {
        "settings": "设置"
      }
    },
    "navigation": {
      "home": "首页",
      "components": "组件",
      "layouts": "布局",
      "about": "关于",
      "settings": "设置",
      "account": "账户",
      "login": "登录",
      "dashboard": "仪表板",
      "someOtherLink": "其他链接",
      "childLinksTitle": {
        "uiComponents": "用户界面组件",
        "uiLayouts": "用户界面布局",
        "settings": "设置",
        "manageAccount": "管理您的账户"
      },
      "placeholderLink": "占位链接",
      "screenReader": {
        "settings": "设置"
      }
    }
  },
  "global": {
    "siteName": "SRCDEV Design System"
  },
  "pages": {
    "account": {
      "login": {
        "header": "登录到您的帐户",
        "description": "使用您的电子邮件和密码访问您的帐户。"
      }
    },
    "index": {
      "header": "SRCDEV Design System",
      "description": "视觉演示排版、布局和组件。"
    },
    "settings": {
      "locale-switcher": {
        "header": "选择语言",
        "description": "从列表中选择您首选的语言。"
      }
    }
  }
} as const