// Auto-generated locale file for zh-CN
// This file is generated by running 'npm run build:i18n'
// Do not edit this file directly - edit the JSON files in i18n/locales/ instead

export default {
  "components": {
    "footer": {
      "home": "首页",
      "components": "组件",
      "layouts": "布局",
      "about": "关于",
      "settings": "设置",
      "account": "账户",
      "login": "登录",
      "dashboard": "仪表板",
      "someOtherLink": "其他链接",
      "childLinksTitle": {
        "uiComponents": "用户界面组件",
        "uiLayouts": "用户界面布局",
        "settings": "设置",
        "manageAccount": "管理您的账户"
      },
      "placeholderLink": "占位链接",
      "screenReader": {
        "settings": "设置"
      }
    },
    "navigation": {
      "home": "首页",
      "components": "组件",
      "layouts": "布局",
      "about": "关于",
      "settings": "设置",
      "account": "账户",
      "login": "登录",
      "dashboard": "仪表板",
      "someOtherLink": "其他链接",
      "childLinksTitle": {
        "uiComponents": "用户界面组件",
        "uiLayouts": "用户界面布局",
        "settings": "设置",
        "manageAccount": "管理您的账户"
      },
      "placeholderLink": "占位链接",
      "screenReader": {
        "settings": "设置"
      }
    }
  },
  "global": {
    "siteName": "SRCDEV Design System"
  },
  "errors": {
    "404": {
      "title": "页面未找到",
      "description": "抱歉，我们无法找到您要找的页面。它可能已被移动、删除，或者网址可能不正确。",
      "help": "这通常发生在页面已被移动或删除，或者网址中有拼写错误时。",
      "suggestions": {
        "checkUrl": "检查网址是否有拼写错误",
        "useNavigation": "使用导航菜单查找您需要的内容",
        "searchContent": "尝试搜索您要找的内容"
      }
    },
    "500": {
      "title": "内部服务器错误",
      "description": "我们这边出了点问题。我们正在努力解决这个问题。",
      "help": "这是我们服务器的临时问题。请稍等片刻后再试。"
    },
    "serverError": {
      "title": "服务器错误",
      "description": "我们遇到了技术困难。请稍后再试。",
      "help": "我们的服务器暂时不可用。这种情况通常很快就能解决。",
      "suggestions": {
        "refresh": "稍等片刻后刷新页面",
        "wait": "等待几分钟后再试",
        "contact": "如果问题持续存在，请联系我们"
      }
    },
    "general": {
      "title": "出现了问题",
      "description": "发生了意外错误。请重试，如果问题持续存在，请联系客服。"
    },
    "actions": {
      "goHome": "回到首页",
      "tryAgain": "重试"
    },
    "help": {
      "moreInfo": "我能做什么？"
    },
    "contact": {
      "text": "如果此问题继续存在，请告知我们：",
      "link": "联系客服"
    }
  },
  "pages": {
    "account": {
      "forgotten-password": {
        "header": "忘记密码",
        "description": "使用您的电子邮件重置密码。"
      },
      "login": {
        "header": "登录到您的帐户",
        "description": "使用您的电子邮件和密码访问您的帐户。"
      }
    },
    "index": {
      "header": "SRCDEV Design System",
      "description": "视觉演示排版、布局和组件。",
      "exampleI18nTitle": "来自 i18n 的示例数据",
      "exampleI18nArray": [
        {
          "id": "exampleValue",
          "name": "示例值",
          "count": 3,
          "items": [
            {
              "id": "item1",
              "name": "项目 1"
            },
            {
              "id": "item2",
              "name": "项目 2"
            },
            {
              "id": "item3",
              "name": "项目 3"
            }
          ]
        },
        {
          "id": "exampleValue2",
          "name": "示例值 2",
          "count": 5,
          "items": [
            {
              "id": "item4",
              "name": "项目 4"
            },
            {
              "id": "item5",
              "name": "项目 5"
            }
          ]
        },
        {
          "id": "exampleValue3",
          "name": "示例值 3",
          "count": 2,
          "items": [
            {
              "id": "item6",
              "name": "项目 6"
            },
            {
              "id": "item7",
              "name": "项目 7"
            }
          ]
        },
        {
          "id": "exampleValue4",
          "name": "示例值 4",
          "count": 0,
          "items": []
        }
      ]
    },
    "settings": {
      "colour-mode-switcher": {
        "header": "切换颜色模式",
        "description": "选择您偏好的颜色模式，或设置为\"自动\"以跟随系统设置"
      },
      "locale-switcher": {
        "header": "选择语言",
        "description": "从列表中选择您首选的语言。"
      }
    }
  }
} as const