// Auto-generated locale file for zh-CN
// This file is generated by running 'npm run build:i18n'
// Do not edit this file directly - edit the JSON files in i18n/locales/ instead

export default {
  "components": {
    "footer": {
      "home": "首页",
      "components": "组件",
      "layouts": "布局",
      "about": "关于",
      "settings": "设置",
      "account": "账户",
      "login": "登录",
      "dashboard": "仪表板",
      "someOtherLink": "其他链接",
      "childLinksTitle": {
        "uiComponents": "用户界面组件",
        "uiLayouts": "用户界面布局",
        "settings": "设置",
        "manageAccount": "管理您的账户"
      },
      "placeholderLink": "占位链接",
      "screenReader": {
        "settings": "设置"
      }
    },
    "navigation": {
      "home": "首页",
      "components": "组件",
      "layouts": "布局",
      "about": "关于",
      "settings": "设置",
      "account": "账户",
      "login": "登录",
      "dashboard": "仪表板",
      "someOtherLink": "其他链接",
      "childLinksTitle": {
        "uiComponents": "用户界面组件",
        "uiLayouts": "用户界面布局",
        "settings": "设置",
        "manageAccount": "管理您的账户"
      },
      "placeholderLink": "占位链接",
      "screenReader": {
        "settings": "设置"
      }
    }
  },
  "global": {
    "siteName": "SRCDEV Design System"
  },
  "pages": {
    "account": {
      "forgotten-password": {
        "header": "忘记密码",
        "description": "使用您的电子邮件重置密码。"
      },
      "login": {
        "header": "登录到您的帐户",
        "description": "使用您的电子邮件和密码访问您的帐户。"
      }
    },
    "index": {
      "header": "SRCDEV Design System",
      "description": "视觉演示排版、布局和组件。",
      "exampleI18nTitle": "来自 i18n 的示例数据",
      "exampleI18nArray": [
        {
          "id": "exampleValue",
          "name": "示例值",
          "count": 3,
          "items": [
            {
              "id": "item1",
              "name": "项目 1"
            },
            {
              "id": "item2",
              "name": "项目 2"
            },
            {
              "id": "item3",
              "name": "项目 3"
            }
          ]
        },
        {
          "id": "exampleValue2",
          "name": "示例值 2",
          "count": 5,
          "items": [
            {
              "id": "item4",
              "name": "项目 4"
            },
            {
              "id": "item5",
              "name": "项目 5"
            }
          ]
        },
        {
          "id": "exampleValue3",
          "name": "示例值 3",
          "count": 2,
          "items": [
            {
              "id": "item6",
              "name": "项目 6"
            },
            {
              "id": "item7",
              "name": "项目 7"
            }
          ]
        },
        {
          "id": "exampleValue4",
          "name": "示例值 4",
          "count": 0,
          "items": []
        }
      ]
    },
    "settings": {
      "colour-mode-switcher": {
        "header": "切换颜色模式",
        "description": "选择您偏好的颜色模式，或设置为\"自动\"以跟随系统设置"
      },
      "locale-switcher": {
        "header": "选择语言",
        "description": "从列表中选择您首选的语言。"
      }
    }
  }
} as const