import type { App } from 'vue'

// 🤖 AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// This file is generated by scripts/generate-storybook-components.mjs
// Run 'npm run storybook:generate-components' to regenerate

async function importComponent(path: string) {
  try {
    const component = await import(/* @vite-ignore */ path)
    return component.default
  } catch (error) {
    console.warn(`Failed to load component from ${path}:`, error)
    return null
  }
}

// Component paths extracted from .nuxt/types/components.d.ts
const componentPaths = {
  MarkdownNuxtLink: "../../app/components/custom-markdown-components/MarkdownNuxtLink.vue",
  RawText: "../../app/components/custom-markdown-components/RawText.vue",
  HeaderNavigation: "../../app/components/header-navigation/HeaderNavigation.vue",
  LocaleSwitcher: "../../app/components/locale-switcher/LocaleSwitcher.vue",
  RenderMarkdownSectionNav: "../../app/components/markdown-rendering/RenderMarkdownSectionNav.vue",
  RenderMarkdownSections: "../../app/components/markdown-rendering/RenderMarkdownSections.vue",
  TestStorybook: "../../app/components/test-storybook/TestStorybook.vue",
  ThemeComponentSwitcher: "../../app/components/theme-switcher/ThemeComponentSwitcher.vue",
  ThemeFormSwitcher: "../../app/components/theme-switcher/ThemeFormSwitcher.vue",
  PropValidators: "../../node_modules/srcdev-nuxt-forms/app/components/forms/c12/prop-validators/index",
  Utils: "../../node_modules/srcdev-nuxt-forms/app/components/forms/c12/utils",
  InputError: "../../node_modules/srcdev-nuxt-forms/app/components/forms/form-errors/InputError.vue",
  FormFieldset: "../../node_modules/srcdev-nuxt-forms/app/components/forms/form-fieldset/FormFieldset.vue",
  InputButtonCore: "../../node_modules/srcdev-nuxt-forms/app/components/forms/input-button/InputButtonCore.vue",
  InputButtonConfirm: "../../node_modules/srcdev-nuxt-forms/app/components/forms/input-button/variants/InputButtonConfirm.vue",
  InputButtonSubmit: "../../node_modules/srcdev-nuxt-forms/app/components/forms/input-button/variants/InputButtonSubmit.vue",
  InputCheckboxRadioButton: "../../node_modules/srcdev-nuxt-forms/app/components/forms/input-checkbox-radio/InputCheckboxRadioButton.vue",
  InputCheckboxRadioCore: "../../node_modules/srcdev-nuxt-forms/app/components/forms/input-checkbox-radio/InputCheckboxRadioCore.vue",
  InputCheckboxRadioWithLabel: "../../node_modules/srcdev-nuxt-forms/app/components/forms/input-checkbox-radio/InputCheckboxRadioWithLabel.vue",
  MultipleCheckboxes: "../../node_modules/srcdev-nuxt-forms/app/components/forms/input-checkbox/MultipleCheckboxes.vue",
  SingleCheckbox: "../../node_modules/srcdev-nuxt-forms/app/components/forms/input-checkbox/SingleCheckbox.vue",
  InputDescription: "../../node_modules/srcdev-nuxt-forms/app/components/forms/input-description/InputDescription.vue",
  InputLabel: "../../node_modules/srcdev-nuxt-forms/app/components/forms/input-label/InputLabel.vue",
  InputNumberCore: "../../node_modules/srcdev-nuxt-forms/app/components/forms/input-number/InputNumberCore.vue",
  InputNumberDefault: "../../node_modules/srcdev-nuxt-forms/app/components/forms/input-number/variants/InputNumberDefault.vue",
  MultipleRadiobuttons: "../../node_modules/srcdev-nuxt-forms/app/components/forms/input-radio/MultipleRadiobuttons.vue",
  InputRangeFancyCore: "../../node_modules/srcdev-nuxt-forms/app/components/forms/input-range-fancy/InputRangeFancyCore.vue",
  InputRangeFancyWithLabel: "../../node_modules/srcdev-nuxt-forms/app/components/forms/input-range-fancy/InputRangeFancyWithLabel.vue",
  InputRangeCore: "../../node_modules/srcdev-nuxt-forms/app/components/forms/input-range/InputRangeCore.vue",
  InputRangeDefault: "../../node_modules/srcdev-nuxt-forms/app/components/forms/input-range/variants/InputRangeDefault.vue",
  InputSelectCore: "../../node_modules/srcdev-nuxt-forms/app/components/forms/input-select/InputSelectCore.vue",
  InputSelectWithLabel: "../../node_modules/srcdev-nuxt-forms/app/components/forms/input-select/variants/InputSelectWithLabel.vue",
  InputTextCore: "../../node_modules/srcdev-nuxt-forms/app/components/forms/input-text/InputTextCore.vue",
  InputPasswordWithLabel: "../../node_modules/srcdev-nuxt-forms/app/components/forms/input-text/variants/InputPasswordWithLabel.vue",
  InputTextAsNumberWithLabel: "../../node_modules/srcdev-nuxt-forms/app/components/forms/input-text/variants/InputTextAsNumberWithLabel.vue",
  InputTextWithLabel: "../../node_modules/srcdev-nuxt-forms/app/components/forms/input-text/variants/InputTextWithLabel.vue",
  InputTextareaCore: "../../node_modules/srcdev-nuxt-forms/app/components/forms/input-textarea/InputTextareaCore.vue",
  InputTextareaWithLabel: "../../node_modules/srcdev-nuxt-forms/app/components/forms/input-textarea/variants/InputTextareaWithLabel.vue",
  ToggleSwitchCore: "../../node_modules/srcdev-nuxt-forms/app/components/forms/toggle-switch/ToggleSwitchCore.vue",
  ToggleSwitchCoreOld: "../../node_modules/srcdev-nuxt-forms/app/components/forms/toggle-switch/ToggleSwitchCoreOld.vue",
  ToggleSwitchWithLabel: "../../node_modules/srcdev-nuxt-forms/app/components/forms/toggle-switch/variants/ToggleSwitchWithLabel.vue",
  ToggleSwitchWithLabelInline: "../../node_modules/srcdev-nuxt-forms/app/components/forms/toggle-switch/variants/ToggleSwitchWithLabelInline.vue",
  TripleToggleSwitchCore: "../../node_modules/srcdev-nuxt-forms/app/components/forms/triple-toggle-switch/TripleToggleSwitchCore.vue",
  FormField: "../../node_modules/srcdev-nuxt-forms/app/components/forms/ui/FormField.vue",
  FormWrapper: "../../node_modules/srcdev-nuxt-forms/app/components/forms/ui/FormWrapper.vue",
  ColourSchemeSelect: "../../node_modules/srcdev-nuxt-forms/app/components/utils/colour-scheme-select/ColourSchemeSelect.vue",
  ColourSchemeSelectOld: "../../node_modules/srcdev-nuxt-forms/app/components/utils/colour-scheme-select/ColourSchemeSelectOld.vue",
  DarkModeSwitcher: "../../node_modules/srcdev-nuxt-forms/app/components/utils/dark-mode-switcher/DarkModeSwitcher.vue",
  AccordianCore: "../../node_modules/srcdev-nuxt-components/app/components/accordian/AccordianCore.vue",
  AlertMaskCore: "../../node_modules/srcdev-nuxt-components/app/components/alert-mask/AlertMaskCore.vue",
  AnimatedSvgText: "../../node_modules/srcdev-nuxt-components/app/components/animated-svg-text/AnimatedSvgText.vue",
  CanvasSwitcher: "../../node_modules/srcdev-nuxt-components/app/components/canvas-switcher/CanvasSwitcher.vue",
  CarouselBasic: "../../node_modules/srcdev-nuxt-components/app/components/carousel-basic/CarouselBasic.vue",
  CarouselFlip: "../../node_modules/srcdev-nuxt-components/app/components/carousel-basic/CarouselFlip.vue",
  CarouselInfinite: "../../node_modules/srcdev-nuxt-components/app/components/carousel-basic/CarouselInfinite.vue",
  ClipElement: "../../node_modules/srcdev-nuxt-components/app/components/clip-element/ClipElement.vue",
  ClippedPanel: "../../node_modules/srcdev-nuxt-components/app/components/clipped-panels/ClippedPanel.vue",
  ContainerGlowCore: "../../node_modules/srcdev-nuxt-components/app/components/container-glow/ContainerGlowCore.vue",
  ContentGrid: "../../node_modules/srcdev-nuxt-components/app/components/content-grid/ContentGrid.vue",
  DeepExpandingMenu: "../../node_modules/srcdev-nuxt-components/app/components/deep-expanding-menu/DeepExpandingMenu.vue",
  DeepExpandingMenuOld: "../../node_modules/srcdev-nuxt-components/app/components/deep-expanding-menu/DeepExpandingMenuOld.vue",
  DisplayAvatar: "../../node_modules/srcdev-nuxt-components/app/components/display-avatar/DisplayAvatar.vue",
  DisplayBanner: "../../node_modules/srcdev-nuxt-components/app/components/display-banner/DisplayBanner.vue",
  DisplayCard: "../../node_modules/srcdev-nuxt-components/app/components/display-card/DisplayCard.vue",
  DisplayChip: "../../node_modules/srcdev-nuxt-components/app/components/display-chip/DisplayChip.vue",
  DisplayDetailsCore: "../../node_modules/srcdev-nuxt-components/app/components/display-details/DisplayDetailsCore.vue",
  DisplayDialogCore: "../../node_modules/srcdev-nuxt-components/app/components/display-dialog/DisplayDialogCore.vue",
  DisplayDialogConfirm: "../../node_modules/srcdev-nuxt-components/app/components/display-dialog/variants/DisplayDialogConfirm.vue",
  DisplayDialogScrollableContent: "../../node_modules/srcdev-nuxt-components/app/components/display-dialog/variants/DisplayDialogScrollableContent.vue",
  DisplayPromptCore: "../../node_modules/srcdev-nuxt-components/app/components/display-prompt/DisplayPromptCore.vue",
  DisplayPromptError: "../../node_modules/srcdev-nuxt-components/app/components/display-prompt/variants/DisplayPromptError.vue",
  DisplayToast: "../../node_modules/srcdev-nuxt-components/app/components/display-toast/DisplayToast.vue",
  ExpandingPanel: "../../node_modules/srcdev-nuxt-components/app/components/expanding-panel/ExpandingPanel.vue",
  GlowingBorder: "../../node_modules/srcdev-nuxt-components/app/components/glowing-border/GlowingBorder.vue",
  SliderGallery: "../../node_modules/srcdev-nuxt-components/app/components/image-galleries/SliderGallery.vue",
  LayoutGridA: "../../node_modules/srcdev-nuxt-components/app/components/layout-grids/LayoutGridA.vue",
  LayoutGridB: "../../node_modules/srcdev-nuxt-components/app/components/layout-grids/LayoutGridB.vue",
  LayoutRow: "../../node_modules/srcdev-nuxt-components/app/components/layout-row/LayoutRow.vue",
  MagneticNavigation: "../../node_modules/srcdev-nuxt-components/app/components/magnetic-navigation/MagneticNavigation.vue",
  MarqueeScroller: "../../node_modules/srcdev-nuxt-components/app/components/marquee-scroller/MarqueeScroller.vue",
  MasonryGridOrdered: "../../node_modules/srcdev-nuxt-components/app/components/masonry-grid-ordered/MasonryGridOrdered.vue",
  MasonryGridSorted: "../../node_modules/srcdev-nuxt-components/app/components/masonry-grid-sorted/MasonryGridSorted.vue",
  MasonryGrid: "../../node_modules/srcdev-nuxt-components/app/components/masonry-grid/MasonryGrid.vue",
  SectionParallax: "../../node_modules/srcdev-nuxt-components/app/components/parallax/SectionParallax.vue",
  PopOver: "../../node_modules/srcdev-nuxt-components/app/components/pop-over/PopOver.vue",
  NavigationItems: "../../node_modules/srcdev-nuxt-components/app/components/responsive-header/NavigationItems.vue",
  ResponsiveHeader: "../../node_modules/srcdev-nuxt-components/app/components/responsive-header/ResponsiveHeader.vue",
  RotatingCarouselImage: "../../node_modules/srcdev-nuxt-components/app/components/rotating-carousel/RotatingCarouselImage.vue",
  SkipLinks: "../../node_modules/srcdev-nuxt-components/app/components/skip-links/SkipLinks.vue",
  TabsCore: "../../node_modules/srcdev-nuxt-components/app/components/tabs/TabsCore.vue",
  HeaderBlock: "../../node_modules/srcdev-nuxt-components/app/components/typography/HeaderBlock.vue",
  UiBlockDecorated: "../../node_modules/srcdev-nuxt-components/app/components/ui-block-decorated/UiBlockDecorated.vue",
  WipeAwayVertical: "../../node_modules/srcdev-nuxt-components/app/components/view-timeline/WipeAwayVertical.vue",
  AuthState: "../../node_modules/nuxt-auth-utils/dist/runtime/app/components/AuthState.vue",
  ProseA: "../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseA.vue",
  ProseBlockquote: "../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseBlockquote.vue",
  ProseCode: "../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseCode.vue",
  ProseEm: "../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseEm.vue",
  ProseH1: "../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH1.vue",
  ProseH2: "../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH2.vue",
  ProseH3: "../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH3.vue",
  ProseH4: "../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH4.vue",
  ProseH5: "../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH5.vue",
  ProseH6: "../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH6.vue",
  ProseHr: "../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseHr.vue",
  ProseImg: "../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseImg.vue",
  ProseLi: "../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseLi.vue",
  ProseOl: "../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseOl.vue",
  ProseP: "../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseP.vue",
  ProsePre: "../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProsePre.vue",
  ProseScript: "../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseScript.vue",
  ProseStrong: "../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseStrong.vue",
  ProseTable: "../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTable.vue",
  ProseTbody: "../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTbody.vue",
  ProseTd: "../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTd.vue",
  ProseTh: "../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTh.vue",
  ProseThead: "../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseThead.vue",
  ProseTr: "../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTr.vue",
  ProseUl: "../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseUl.vue",
  NuxtWelcome: "../../node_modules/nuxt/dist/app/components/welcome.vue",
  DevOnly: "../../node_modules/nuxt/dist/app/components/dev-only",
  ServerPlaceholder: "../../node_modules/nuxt/dist/app/components/server-placeholder",
  NuxtTime: "../../node_modules/nuxt/dist/app/components/nuxt-time.vue",
  NuxtRouteAnnouncer: "../../node_modules/nuxt/dist/app/components/nuxt-route-announcer",
  NuxtPicture: "../../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue",
  NuxtLinkLocale: "../../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale",
  SwitchLocalePathLink: "../../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink",
  ContentRenderer: "../../node_modules/@nuxt/content/dist/runtime/components/ContentRenderer.vue",
  MDC: "../../node_modules/@nuxtjs/mdc/dist/runtime/components/MDC.vue",
  MDCCached: "../../node_modules/@nuxtjs/mdc/dist/runtime/components/MDCCached.vue",
  MDCRenderer: "../../node_modules/@nuxtjs/mdc/dist/runtime/components/MDCRenderer.vue",
  MDCSlot: "../../node_modules/@nuxtjs/mdc/dist/runtime/components/MDCSlot.vue",
  NuxtIsland: "../../node_modules/nuxt/dist/app/components/nuxt-island",
} as const

// All available components (auto-discovered from Nuxt)
const availableComponents = [
  'MarkdownNuxtLink',
  'RawText',
  'HeaderNavigation',
  'LocaleSwitcher',
  'RenderMarkdownSectionNav',
  'RenderMarkdownSections',
  'TestStorybook',
  'ThemeComponentSwitcher',
  'ThemeFormSwitcher',
  'PropValidators',
  'Utils',
  'InputError',
  'FormFieldset',
  'InputButtonCore',
  'InputButtonConfirm',
  'InputButtonSubmit',
  'InputCheckboxRadioButton',
  'InputCheckboxRadioCore',
  'InputCheckboxRadioWithLabel',
  'MultipleCheckboxes',
  'SingleCheckbox',
  'InputDescription',
  'InputLabel',
  'InputNumberCore',
  'InputNumberDefault',
  'MultipleRadiobuttons',
  'InputRangeFancyCore',
  'InputRangeFancyWithLabel',
  'InputRangeCore',
  'InputRangeDefault',
  'InputSelectCore',
  'InputSelectWithLabel',
  'InputTextCore',
  'InputPasswordWithLabel',
  'InputTextAsNumberWithLabel',
  'InputTextWithLabel',
  'InputTextareaCore',
  'InputTextareaWithLabel',
  'ToggleSwitchCore',
  'ToggleSwitchCoreOld',
  'ToggleSwitchWithLabel',
  'ToggleSwitchWithLabelInline',
  'TripleToggleSwitchCore',
  'FormField',
  'FormWrapper',
  'ColourSchemeSelect',
  'ColourSchemeSelectOld',
  'DarkModeSwitcher',
  'AccordianCore',
  'AlertMaskCore',
  'AnimatedSvgText',
  'CanvasSwitcher',
  'CarouselBasic',
  'CarouselFlip',
  'CarouselInfinite',
  'ClipElement',
  'ClippedPanel',
  'ContainerGlowCore',
  'ContentGrid',
  'DeepExpandingMenu',
  'DeepExpandingMenuOld',
  'DisplayAvatar',
  'DisplayBanner',
  'DisplayCard',
  'DisplayChip',
  'DisplayDetailsCore',
  'DisplayDialogCore',
  'DisplayDialogConfirm',
  'DisplayDialogScrollableContent',
  'DisplayPromptCore',
  'DisplayPromptError',
  'DisplayToast',
  'ExpandingPanel',
  'GlowingBorder',
  'SliderGallery',
  'LayoutGridA',
  'LayoutGridB',
  'LayoutRow',
  'MagneticNavigation',
  'MarqueeScroller',
  'MasonryGridOrdered',
  'MasonryGridSorted',
  'MasonryGrid',
  'SectionParallax',
  'PopOver',
  'NavigationItems',
  'ResponsiveHeader',
  'RotatingCarouselImage',
  'SkipLinks',
  'TabsCore',
  'HeaderBlock',
  'UiBlockDecorated',
  'WipeAwayVertical',
  'AuthState',
  'ProseA',
  'ProseBlockquote',
  'ProseCode',
  'ProseEm',
  'ProseH1',
  'ProseH2',
  'ProseH3',
  'ProseH4',
  'ProseH5',
  'ProseH6',
  'ProseHr',
  'ProseImg',
  'ProseLi',
  'ProseOl',
  'ProseP',
  'ProsePre',
  'ProseScript',
  'ProseStrong',
  'ProseTable',
  'ProseTbody',
  'ProseTd',
  'ProseTh',
  'ProseThead',
  'ProseTr',
  'ProseUl',
  'NuxtWelcome',
  'DevOnly',
  'ServerPlaceholder',
  'NuxtTime',
  'NuxtRouteAnnouncer',
  'NuxtPicture',
  'NuxtLinkLocale',
  'SwitchLocalePathLink',
  'ContentRenderer',
  'MDC',
  'MDCCached',
  'MDCRenderer',
  'MDCSlot',
  'NuxtIsland',
] as const

export async function registerComponents(app: App, componentsToRegister?: string[]) {
  // Register all components by default, or only specified ones
  const targetComponents = componentsToRegister || availableComponents

  for (const componentName of targetComponents) {
    const path = componentPaths[componentName as keyof typeof componentPaths]
    if (path) {
      const component = await importComponent(path)
      if (component) {
        app.component(componentName, component)
        console.log(`✅ Registered component: ${componentName}`)
      }
    } else {
      console.warn(`⚠️  Component ${componentName} not found in component paths`)
    }
  }
}

// Helper function to register a specific component on demand
export async function registerComponent(app: App, componentName: keyof typeof componentPaths) {
  const path = componentPaths[componentName]
  if (path) {
    const component = await importComponent(path)
    if (component) {
      app.component(componentName, component)
      console.log(`✅ Registered component: ${componentName}`)
      return true
    }
  }
  return false
}

export function registerNuxtMocks(app: App) {
  // Mock Nuxt framework components
  app.component('Icon', {
    props: {
      name: { type: String, required: true },
      size: { type: [String, Number], default: '1em' },
    },
    template: `
      <span
        :style="{
          display: 'inline-block',
          width: typeof size === 'number' ? size + 'px' : size,
          height: typeof size === 'number' ? size + 'px' : size,
          backgroundColor: 'currentColor',
          maskImage: 'url(https://api.iconify.design/' + name.replace(':', '/') + '.svg)',
          maskRepeat: 'no-repeat',
          maskPosition: 'center',
          maskSize: 'contain'
        }"
        :title="name"
      ></span>
    `,
  })

  app.component('NuxtImg', {
    props: {
      src: { type: String, required: true },
      alt: { type: String, default: '' },
      width: { type: [String, Number] },
      height: { type: [String, Number] },
      loading: { type: String, default: 'lazy' },
    },
    template: `
      <img
        :src="src"
        :alt="alt"
        :width="width"
        :height="height"
        :loading="loading"
        v-bind="$attrs"
      />
    `,
  })

  app.component('NuxtLink', {
    props: {
      to: { type: [String, Object], required: true },
      external: { type: Boolean, default: false },
    },
    template: `
      <a
        :href="typeof to === 'string' ? to : to.path || to.href"
        :target="external ? '_blank' : undefined"
        :rel="external ? 'noopener noreferrer' : undefined"
        v-bind="$attrs"
      >
        <slot />
      </a>
    `,
  })

  app.component('ClientOnly', {
    template: `<slot />`,
  })

  app.component('NuxtLayout', {
    props: {
      name: { type: String, default: 'default' },
    },
    template: `
      <div class="nuxt-layout">
        <slot />
      </div>
    `,
  })
}

// Export component info for debugging
export const componentInfo = {
  totalComponents: availableComponents.length,
  availableComponents,
  componentPaths,
}
